### ISSUE TITLE
Using CircularArrayBuffers for non-iterable data

### ISSUE THREAD

**Issue by 3rdCore** [JuliaReinforcementLearning/CircularArrayBuffers.jl#12]
Hello, I have an issue regarding the latest updates of the package _CircularArrayBuffers.jl_

I am using the package ReinforcementLearning.jl to train a RL-based agent to make decisions on graphs. The trajectory is stored in a `CircularArraySARTTrajectory` object, in which environment states are stored in a `CircularArrayBuffers`. 

In my case, my environment state is a custom class called `DefaultTrajectoryState` which is a non-tabular data. However, since the latest update of the package, CircularArrayBuffers expects the data to be `iterable` in order to be broadcasted for the case we want to push multiple states in the `CircularArrayBuffers`, which is not my case. 
I getthe following error : 
`Got exception outside of a @test
  MethodError: no method matching iterate(::SeaPearl.DefaultTrajectoryState)`

The error comes from the following function of _CircularArrayBuffers.jl_ : 
```julia
function Base.push!(cb::CircularArrayBuffer{T,N}, data) where {T,N}
    if cb.nframes == capacity(cb)
        cb.first = (cb.first == capacity(cb) ? 1 : cb.first + 1)
    else
        cb.nframes += 1
    end
    if N == 1
        i = _buffer_frame(cb, cb.nframes)
        if ndims(data) == 0
            cb.buffer[i:i] .= data[]
        else
            cb.buffer[i:i] .= data                    <----- ERROR
        end
    else
        cb.buffer[ntuple(_ -> (:), N - 1)..., _buffer_frame(cb, cb.nframes)] .= data
    end
    cb
end
```

It is designed "on purpose"? Knowing that should I consider encapsulating my state into a Vector containing one single element?

**Comment by 3rdCore** [comment]
One solution I found was to virtually overwrite the base function iterate and directly return the element.

**Comment by findmyway** [comment]
> One solution I found was to virtually overwrite the base function iterate and directly return the element.

Yeah, this will do the trick.

Previously, the `data` is assumed to be an `AbstractArray` or a `Number`. So a customized data type is not taken into account. Let me have a think of how to remove this assumption.

**Comment by findmyway** [comment]
A MWE:

```julia
julia> b = CircularArrayBuffer([:a, :b])
CircularVectorBuffer(::Vector{Symbol}) with eltype Symbol:
 :a
 :b

julia> push!(b, :c)
ERROR: MethodError: no method matching ndims(::Symbol)
Closest candidates are:
  ndims(::Base.Generator) at /mnt/E4E0A9C0E0A998F6/software/julia-1.7.1/share/julia/base/generator.jl:53
  ndims(::Base.Broadcast.Broadcasted{<:Any, <:Tuple{Vararg{Any, N}}}) where N at /mnt/E4E0A9C0E0A998F6/software/julia-1.7.1/share/julia/base/broadcast.jl:247
  ndims(::Base.Iterators.ProductIterator) at /mnt/E4E0A9C0E0A998F6/software/julia-1.7.1/share/julia/base/iterators.jl:983
  ...
Stacktrace:
 [1] push!(cb::CircularVectorBuffer{Symbol, Vector{Symbol}}, data::Symbol)
   @ CircularArrayBuffers /mnt/E4E0A9C0E0A998F6/github/CircularArrayBuffers.jl/src/CircularArrayBuffers.jl:95
 [2] top-level scope
   @ REPL[4]:1
```

**Comment by darsnack** [comment]
> I think here it was meant to overcome the scalar operation when processing CuArrays. @darsnack may confirm this.

That's correct, and I did not consider about the non-numeric case here.

**Comment by findmyway** [comment]
@JuliaRegistrator register

**Comment by 3rdCore** [comment]
Thanks for the support guys ! 

Amazing work !
