### ISSUE TITLE
CircularArrayBuffers.jl bug related to :Colon type and _buffer_frame function

### ISSUE THREAD

**Issue by 3rdCore** [JuliaReinforcementLearning/CircularArrayBuffers.jl#14]
Hello, I re-ran my testsets after the yesterday's fix of CircularArrayBuffers.jl mentionned [here](https://github.com/JuliaReinforcementLearning/CircularArrayBuffers.jl/issues/12) and there is still a bug that I can't track and I don't think I comes from my package : 

```julia
Got exception outside of a @test
  MethodError: no method matching _buffer_frame(::CircularArrayBuffers.CircularArrayBuffer{Float32, 2, Matrix{Float32}}, ::Colon)
  Closest candidates are:
    _buffer_frame(::CircularArrayBuffers.CircularArrayBuffer, ::Int64) at /home/runner/.julia/packages/CircularArrayBuffers/kB44S/src/CircularArrayBuffers.jl:89
    _buffer_frame(::CircularArrayBuffers.CircularArrayBuffer, ::AbstractArray{var"#s1", N} where {var"#s1"<:Integer, N}) at /home/runner/.julia/packages/CircularArrayBuffers/kB44S/src/CircularArrayBuffers.jl:99
```   

This is the first time I heard about the type `::Colon`. Maybe you guys can help me on this. The error was triggered when I tried to add a step to my trajectory, the only difference to my other testsets that passes is that the agent uses an A2C learner. 

You can find the entire StackTrace [here](https://github.com/corail-research/SeaPearl.jl/pull/204/checks) and the agent definition [here ](https://github.com/corail-research/SeaPearl.jl/blob/master/test/CP/core/search/rbs.jl) starting line 398.

**Comment by findmyway** [comment]
Yet another corner case not covered.

`Colon()` is just the alias of the `:` symbol in array indexing.

**Comment by findmyway** [comment]
@JuliaRegistrator register
