### ISSUE TITLE
Comparison with CircularArrays.jl

### ISSUE THREAD

**Issue by fedario** [JuliaReinforcementLearning/CircularArrayBuffers.jl#2]
Hi,
how does this package compare to CircularArrays.jl?

https://github.com/Vexatos/CircularArrays.jl

**Comment by findmyway** [comment]
Well, the difference is obvious, we are **Buffers**. 😆 

> It has a fixed size and features circular indexing (periodic boundary conditions) across all dimensions: Indexing and assigning beyond its bounds in both directions is possible, as the end of the array is considered adjacent to its start.

Based on the description above from `CircularArrays.jl`, a `CircularArray` has a **fixed** size. In comparison, `CircularArrayBuffer` has a variable size with a pre-allocated buffer. You can `push!` elements into it. And when the buffer is full, the oldest data will be overridden. I think this package is more close to the `CircularBuffer` in [DataStructures.jl](https://juliacollections.github.io/DataStructures.jl/latest/circ_buffer/), except that when dealing with Arrays, we use a pre-allocated **continuous** array as the underlying storage instead of a **Vector**.

**Comment by fedario** [comment]
Thank you for your quick answer!

I tried your package and it is pretty cool!
Would it be possible (and feasible) to add an `append!` function behaving similar to that of `CircularBuffer` in DataStructures.jl?

Also did you consider adding this type to DataStructures.jl?

**Comment by findmyway** [comment]
> Would it be possible (and feasible) to add an append! function behaving similar to that of CircularBuffer in DataStructures.jl?

Yes, of course. Could you be more specific about the signature of `append!`? 

- Like `append!(buffer::CircularArrayBuffer, xs::Vector{<:Array})` to append a vector of elements
- Or `append!(buffer::CircularArrayBuffer, xs::Array)` to append a continuous array of elements?

> Also did you consider adding this type to DataStructures.jl?

Yes, but it seems they don't want to add more new data structures until v1.0  https://github.com/JuliaCollections/DataStructures.jl/issues/479

> Btw: I found it by luck when using autocompletion on "CircularA" when wanting to install CircularArrays (however, your package is what I actually required).

I learned something new 😄

**Comment by fedario** [comment]
> > Also did you consider adding this type to DataStructures.jl?
> 
> Yes, but it seems they don't want to add more new data structures until v1.0 [JuliaCollections/DataStructures.jl#479](https://github.com/JuliaCollections/DataStructures.jl/issues/479)

Oh, there seems to be a lot of discussion, I see.

> 
> > Btw: I found it by luck when using autocompletion on "CircularA" when wanting to install CircularArrays (however, your package is what I actually required).
> 
> I learned something new smile

:smile: 

> > Would it be possible (and feasible) to add an append! function behaving similar to that of CircularBuffer in DataStructures.jl?
> 
> Yes, of course. Could you be more specific about the signature of `append!`?
> 
>     * Like `append!(buffer::CircularArrayBuffer, xs::Vector{<:Array})` to append a vector of elements
> 
>     * Or `append!(buffer::CircularArrayBuffer, xs::Array)` to append a continuous array of elements?
> 

For me personally the second case would be more fitting.
