### ISSUE TITLE
Push single values to a multidimensional array?

### ISSUE THREAD

**Issue by robsmith11** [JuliaReinforcementLearning/CircularArrayBuffers.jl#4]
Thanks for sharing this package.  It's a very useful data structure to use when I write simulations and need moving windows of multidimensional data.

I was surprised by the behavior of `push!` at first:
```
julia> a = CircularArrayBuffer(zeros(4,3))
4×3 CircularArrayBuffer{Float64, 2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> push!(a, 0.5)
4×3 CircularArrayBuffer{Float64, 2}:
 0.0  0.0  0.5
 0.0  0.0  0.5
 0.0  0.0  0.5
 0.0  0.0  0.5
```
On second thought, it of course makes sense that this behavior is useful in some situations, but would it also be possible and make sense to add another function or add an option to `push!` that would allow one to efficiently push single values?

Something like:
```
julia> push!(a, 0.5, broadcast=false)
4×3 CircularArrayBuffer{Float64, 2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.5
```

**Comment by findmyway** [comment]
Hello @robsmith11 ,

Actually the first case you shown above is an unexpected error.

I should have added a check at:

https://github.com/JuliaReinforcementLearning/CircularArrayBuffers.jl/blob/08852230c752dd67128a17505cd2cb19b6db8aa2/src/CircularArrayBuffers.jl#L68 to make sure that the length of `data` should match `buffer.step_size`.

What you want in the second example is kind of unclear to me.

Let's say we have a buffer like this:

```julia

julia> b = CircularArrayBuffer{Int}(3,2)
3×0 CircularArrayBuffer{Int64, 2}

julia> push!(b, [1,1,1])
3×1 CircularArrayBuffer{Int64, 2}:
 1
 1
 1

julia> push!(b, [2,2,2])
3×2 CircularArrayBuffer{Int64, 2}:
 1  2
 1  2
 1  2
```
Then after executing `push!(b, 3)`, do you wish to have
```
julia> [1 2; 1 2; 2 3]
3×2 Matrix{Int64}:
 1  2
 1  2
 2  3
```

?

This somewhat violates my assumption above （the length of each element should be the same with the `step_size`).
And I think in this case, the buffer is just a `CircularVectorBuffer`. So you can achieve the same goal with it like this:

```julia
julia> b = CircularVectorBuffer{Int}(6)
0-element CircularVectorBuffer{Int64}

julia> append!(b, 1:3)
3-element CircularVectorBuffer{Int64}:
 1
 2
 3

julia> append!(b, 4:6)
6-element CircularVectorBuffer{Int64}:
 1
 2
 3
 4
 5
 6

julia> append!(b, 7)
6-element CircularVectorBuffer{Int64}:
 2
 3
 4
 5
 6
 7

julia> reshape(b, 3, 2)
3×2 reshape(::CircularVectorBuffer{Int64}, 3, 2) with eltype Int64:
 2  5
 3  6
 4  7
```

**Comment by robsmith11** [comment]
Ah thanks for the tip.  I had tried using `reshape` with a standard vector, but wasn't able to `pop!` and `push!` after `reshape` because that would mean resizing and shared array.  But pushing to a circular vector after reshaping does indeed still work.
