### ISSUE TITLE
Allow GPU support?

### ISSUE THREAD

**Issue by darsnack** [JuliaReinforcementLearning/CircularArrayBuffers.jl#8]
The current type for `CircularArrayBuffer` only allows the backing array to be an `Array`. Can this be relaxed to allow `CuArray`s (or any `AbstractArray`)? AFAICT scalar indexing is not introduced by the package code (meaning scalar indexing should only trigger if a user is scalar indexing in the first place).

You might also consider adding an Adapt.jl rule:
```julia
Adapt.adapt_structure(to, x::CircularArrayBuffer) =
    CircularArrayBuffer(adapt(to, x.buffer), x.first, x.nframes, x.step_size)
```

**Comment by findmyway** [comment]
@JuliaRegistrator register
